#!/usr/bin/env python3
"""
Data generation pipeline for kids Spanish learning library.

Reads words.txt and produces data.json with:
  - Spanish and Chinese translations
  - English definition (kid-friendly)
  - Simple Spanish sample sentence
  - An emoji to represent the word (used as image placeholder)

Audio is handled in the browser via the Web Speech API (no downloads needed).
"""

import json
import os

import requests
import anthropic

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_FILE  = os.path.join(SCRIPT_DIR, "data.json")
WORDS_FILE = os.path.join(SCRIPT_DIR, "words.txt")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_words() -> list[str]:
    with open(WORDS_FILE, encoding="utf-8") as f:
        return [line.strip() for line in f if line.strip()]


def get_anthropic_client() -> anthropic.Anthropic:
    """Build an Anthropic client.

    Supports the Apple corporate proxy (localhost:5522) which uses OIDC tokens,
    as well as a standard ANTHROPIC_API_KEY environment variable.
    """
    base_url = os.environ.get("ANTHROPIC_BASE_URL", "")
    if base_url:
        try:
            resp = requests.get(f"{base_url}/api/token", timeout=5)
            token = resp.json().get("token", "")
            if token:
                return anthropic.Anthropic(auth_token=token, base_url=base_url)
        except Exception:
            pass
    return anthropic.Anthropic()


def generate_word_data(words: list[str]) -> list[dict]:
    """Ask Claude for translations, definitions, sentences, and an emoji."""
    client = get_anthropic_client()

    prompt = f"""For each English word below, produce data for a kids Spanish learning app.

Words: {', '.join(words)}

Return ONLY a JSON array. Each object must have exactly these keys:
  "english"    – the original English word
  "spanish"    – Spanish translation (word or short phrase)
  "chinese"    – simplified Chinese translation (word or short phrase)
  "definition" – one plain-English sentence a young child can understand
  "emoji"      – a single emoji that best represents the word

Example element:
{{
  "english": "cat",
  "spanish": "gato",
  "chinese": "猫",
  "definition": "A small furry animal that purrs and says meow.",
  "emoji": "🐱"
}}"""

    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=1024,
        messages=[{"role": "user", "content": prompt}],
    )

    text = message.content[0].text.strip()
    # Strip markdown code fences if Claude wrapped the JSON
    if text.startswith("```"):
        text = text.split("```")[1]
        if text.startswith("json"):
            text = text[4:]
    return json.loads(text.strip())


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    words = load_words()
    print(f"Loaded {len(words)} words: {', '.join(words)}\n")

    print("Generating translations, definitions, and emojis with Claude …")
    word_data = generate_word_data(words)
    print(f"Received data for {len(word_data)} words.\n")

    for entry in word_data:
        print(f"  {entry['english']:12}  →  {entry['spanish']:12}  {entry['chinese']:6}  {entry['emoji']}")

    with open(DATA_FILE, "w", encoding="utf-8") as f:
        json.dump(word_data, f, ensure_ascii=False, indent=2)
    print(f"\n✓  Saved data.json with {len(word_data)} entries.")

    # Also write data.js so index.html can load it directly from the filesystem
    js_file = os.path.join(SCRIPT_DIR, "data.js")
    with open(js_file, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by generate_data.py — do not edit by hand\n")
        f.write("const WORD_DATA = ")
        json.dump(word_data, f, ensure_ascii=False, indent=2)
        f.write(";\n")
    print(f"✓  Saved data.js (loaded by index.html).")

    # Build a standalone single-file HTML for iPhone (no external dependencies)
    html_template = os.path.join(SCRIPT_DIR, "index.html")
    standalone    = os.path.join(SCRIPT_DIR, "standalone.html")
    with open(html_template, encoding="utf-8") as f:
        html = f.read()

    # Merge the data script tag and the following app script tag into ONE block.
    # iOS Safari does not share `const` / `let` across separate <script> tags,
    # so everything must live in a single script execution context.
    data_tag = "<script src=\"data.js\"></script>\n<script>"
    data_inline = (
        "<script>\nconst WORD_DATA = "
        + json.dumps(word_data, ensure_ascii=False, indent=2)
        + ";\n"
    )
    html = html.replace(data_tag, data_inline)

    with open(standalone, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"✓  Saved standalone.html (single file — AirDrop this to iPhone).")


if __name__ == "__main__":
    main()
